global:
  checkNewVersion: true
  sendAnonymousUsage: false

# -- Change Log Level and Format
#     - loglevels [DEBUG, INFO, WARNING, ERROR, CRITICAL]
#     - format [common, json, logfmt]
log:
  level: INFO
  format: common
  filePath: /var/log/traefik/traefik.log

# -- Enable Accesslog and change Format
#     - format [common, json, logfmt]
accesslog:
  format: common
  filePath: /var/log/traefik/access.log

# -- Enable API and Dashboard
api:
  dashboard: true
  disableDashboardAd: true
  insecure: false

# -- Change EntryPoints
entryPoints:
  web:
    address: :80
    # -- Redirect all HTTP to HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
    forwardedHeaders:
      trustedIPs:
        # Cloudflare IPs
        - 173.245.48.0/20
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 141.101.64.0/18
        - 108.162.192.0/18
        - 190.93.240.0/20
        - 188.114.96.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 162.158.0.0/15
        - 104.16.0.0/13
        - 104.24.0.0/14
        - 172.64.0.0/13
        - 131.0.72.0/22
        - 2400:cb00::/32
        - 2606:4700::/32
        - 2803:f800::/32
        - 2405:b500::/32
        - 2405:8100::/32
        - 2a06:98c0::/29
        - 2c0f:f248::/32
        # Localhost
        - 127.0.0.1/32
        - 10.0.0.0/8
        - 192.168.0.0/16
        - 172.16.0.0/12

# -- Configure CertificateResolver
certificatesResolvers:
  production:
    acme:
      email: cs.of.origins@gmail.com
      storage: /etc/traefik/certs/acme.json
      # caServer: "https://acme-v02.api.letsencrypt.org/directory"
      caServer: "https://api.buypass.com/acme/directory"
      # -- Configure HTTP Challenge
      httpChallenge:
        entryPoint: web
      # -- Configure DNS Challenge
      # dnsChallenge:
      #   provider: cloudflare
      #   resolvers:
      #     - "1.1.1.1:53"
      #     - "8.8.8.8:53"

# -- (Optional) Disable TLS Cert verification check
# serversTransport:
#   insecureSkipVerify: true

# -- (Optional) Overwrite Default Certificates
# tls:
#   stores:
#     default:
#       defaultCertificate:
#         certFile: /etc/traefik/certs/cert.pem
#         keyFile: /etc/traefik/certs/cert-key.pem
# -- (Optional) Disable TLS version 1.0 and 1.1
#   options:
#     default:
#       minVersion: VersionTLS12

http:
  middlewares:
    auth:
      forwardAuth:
        address: "http://auth-server:9000/outpost.goauthentik.io/auth/traefik"
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true
